apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: deenk8s-webapp
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/MMuyideen/Azure-cloudops-week4.git
    targetRevision: HEAD
    path: kube_manifest/
  destination: 
    server: https://kubernetes.default.svc
    namespace: deenk8s-webapp

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
