apiVersion: apps/v1
kind: Deployment
metadata:
  name: deenk8s-webapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: deenk8s-webapp
  template:
    metadata:
      labels:
        app: deenk8s-webapp
    spec:
      containers:
      - name: deenk8s-webapp
        image: fullbloodprince/deenk8s-webapp:9aea4a25
        ports:
        - containerPort: 5000
