name: Docker Build and Deploy

on:
  push:
    branches:
      - master

env:
  IMAGE_NAME: deenk8s-webapp
  DOCKER_HUB_USERNAME: fullbloodprince

jobs:

  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Docker login
      run: docker login -u ${{ env.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_ACCESS_TOKEN }}

    - name: Build and push Docker image
      run: |
        pwd
        docker build -t ${{ env.DOCKER_HUB_USERNAME }}/${{ env.IMAGE_NAME }}:${GITHUB_SHA::8} ./APP/
        docker push ${{ env.DOCKER_HUB_USERNAME }}/${{ env.IMAGE_NAME }}:${GITHUB_SHA::8}

    - name: Update Kubernetes manifest
      run: |
        IMAGE_TAG=${GITHUB_SHA::8}
        sed -i "s|image: .*|image: ${{ env.DOCKER_HUB_USERNAME }}/${{ env.IMAGE_NAME }}:$IMAGE_TAG|" kube_manifest/deployment.yaml

    - name: Commit and push manifest changes
      run: |
        git config --global user.name 'Muyideen'
        git config --global user.email '$(GITHUB_EMAIL)'
        git add kube_manifest/deployment.yaml
        git commit -m "Update image tag in deployment.yaml"
        git push

























# name: Week 4 App workflow

# on:
#   push:
#     branches:
#       - main

# env:
#   IMAGE_NAME: deenk8s-webapp      

# jobs:
#   build-and-push:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v4

#       - name: Set up Docker Buildx
#         uses: docker/setup-buildx-action@v3

#       - name: Login to Docker Hub
#         uses: docker/login-action@v3
#         with:
#           username: ${{ secrets.DOCKER_USERNAME }}
#           password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

#       - name: Build and Push Docker image with Layer Caching
#         uses: docker/build-push-action@v5
#         with:
#           context: APP/
#           push: true
#           tags: fullbloodprince/deenk8s-webapp:${{ github.ref_name }}-${{ github.run_number }}
#           cache-from: type=local,src=/tmp/.buildx-cache
#           cache-to: type=local,dest=/tmp/.buildx-cache,mode=max

#       - name: Update Kubernetes manifest
#         run: |
#             IMAGE_TAG=${GITHUB_SHA::8}
#             sed -i "s|image: .*|image: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.IMAGE_NAME }}:$IMAGE_TAG|" kubernetes/deployment.yaml
    
#       - name: Commit and push manifest changes
#         run: |
#             git config --global user.name 'GitHub Actions'
#             git config --global user.email 'github-actions@github.com'
#             git add kubernetes/deployment.yaml
#             git commit -m "Update image tag in deployment.yaml"
#             git push   